### ISSUE TITLE
Does not compile with my linux 4.11...

### ISSUE THREAD

**Issue by yo6ial** [nexx512/txppm#5]
And perhaps newer linux with "raw_copy_from_user" but works great with r = copy_from_user (...);
despite running kernel >4.0
Compiler said implicit declaration of function, and from my limited coding experience, I assumed the raw_copy_from_user does not (no longer?) exist newer linux kernels. 
Fixed by removing/commenting out lines 98, 99, 100 and 102. 
This could be closed right away, I wrote it just to help others with a quick fix. 

Many thanks for this code!!!
Tested with HELI-X v6.x and an Sanwa rds8000 radio. I experienced zero lag or extra jitter.

**Comment by kunalgrover05** [comment]
I am not sure if removing the code lines is safe. 
I was able to compile by changing the header to include: https://stackoverflow.com/questions/46302524/copy-to-user-undefined-in-linux-kernel-version-4-12-8
